name: Guillaume Besson
subtitle: Thoughts of a passionate developer
# Google analytics tracker code, replace with yours if you want
analytics: "<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create', 'UA-37428993-2', 'besson.co');ga('send', 'pageview');</script>"


# Jekyll config
markdown: redcarpet
# For syntaxic coloration in code blocks
pygments: true
# All these files are not necessaries to the site or copied with Grunt
exclude: [css, js, styles.css, script.js, dist, images, node_modules, Gruntfile.js, README.md, package.json, updater.js]
# Permalinks structure : http://jekyllrb.com/docs/permalinks/
permalink: "/:categories/:year/:title/"
